version: '2.2'
services:
  todo:
    container_name: ${PROJECT_NAME}_web
    image: ${PROJECT_NAME}:${RELEASE_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
#    volumes:
#      - ./src:/home/app/src
#    ports:
#      - "${FLASK_PORT:-5000}:${FLASK_PORT:-5000}"
